version: "3.6"
services:
  redis:
    restart: always
    container_name: "redis"
    image: "redis:6-alpine"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
  nginx:
    restart: always
    container_name: "nginx"
    build: "./nginx"
    ports:
      - "80:80"
    networks:
      - app-network
  backend:
    container_name: "backend"
    build: "."
    networks:
      - app-network

networks:
  app-network:
    driver: bridge